sena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('territorio/',),#depues de la segunda coma es para un alias, aun no lo utilizamos

    path('territorio/', include('territorio.urls')),
]

territorio/urls.py
from django.urls import path

from . import views

app_name="territorio"

urlpatterns = [
    path('saludar/', views.saludo, name="saludar"),
    path('saludoEspecial/<str:vari>', views.saludoEspecial, name="saludar"), #vari tiene que ir en el metodo 
    path('calculadora/<int:tipo>/<int:vari>/<int:vari2>', views.calculadora, name="calculadora"), #vari tiene que ir en el metodo 
    path('', views.inicio, name="inicio"),
    path('loginForm/', views.loginForm, name="login-form"),
    path('login/', views.login, name="login"),
]

territorio/models.py
from django.db import models

# Create your models here.

class Aprendiz(models.Model):
    cedula = models.IntegerField() 
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

territorio/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse #print en la web, podemos imprimir cod de html

# Create your views here.
def saludo(request):
    return HttpResponse(f"Hola Mundo! quieres ir al saludo especial? click <a href='/territorio/saludoEspecial/hola'>aqui</a>")

def saludoEspecial(request, vari):
    if vari == "":
        pass
    else:
        return HttpResponse(f"<strong>Hey</strong>, este es un nuevo saludo, por cierto {vari}<br>quieres ir al saludo comun? click <a href='/territorio/saludar'>aqui</a>")

def calculadora(request, tipo, vari, vari2):
    if tipo == 1:
        HttpResponse("sumita")
        return HttpResponse(f"la suma es: <br><strong>{vari} + {vari2} =</strong> <a style='color:red';>{vari + vari2}</a>")
    elif tipo==2:
        return HttpResponse(f"la resta es: <br><strong>{vari} - {vari2} =</strong> <a style='color:red';>{vari - vari2}</a>")
    elif tipo==3:
        return HttpResponse(f"la multiplicacion es: <br><strong>{vari} * {vari2} =</strong> <a style='color:red';>{vari * vari2}</a>")
    elif tipo==4:
        return HttpResponse(f"la division es: <br><strong>{vari} / {vari2} =</strong> <a style='color:red';>{vari/vari2}</a>")

def inicio(request):
    return render(request, 'territorio/index.html')

def loginForm(request):
    return render(request, 'territorio/login/login.html')

def login(request):
    u = request.POST["usuario"]
    c = request.POST["clave"]
    if u == "admin" and c=="1234":
        return HttpResponse(f"Bienvenido {u}")
    else:
        return HttpResponse("acceso denegado")



    

territorio/templates/territorio/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido</title>
    <link rel="stylesheet" href="{% static 'territorio/css/estilos.css' %}">
</head>
<body>
    <h1>Bienvenido a un territorium totalmente nuevo</h1>
    <a href="{% url 'territorio:login-form' %}">Login</a>

    <img src="{% static 'territorio/img/plano.webp' %}" alt="" width="600px" height="400px"><br>
    <button onclick="alertica()">alertica</button>



    <script src="{% static 'territorio/js/funciones.js' %}"></script>
</body>
</html>

territorio/templates/territorio/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form action="{% url 'territorio:login' %}" method="post">
        {% csrf_token %}
        
        <label for="">Usuario</label>
        <input type="text" name="usuario"><br>

        <label for="">Password</label>
        <input type="password" name="clave">

        <button type="submit" >Enviar</button>
    </form>
</body>
</html>